### ISSUE TITLE
`--help` flag pulls images

### ISSUE THREAD

**Issue by enterJazz** [scontain/sconectl#3]
**Expected:** `sconectl apply --help` only displays the `help` message of `sconectl apply`.

**Actual:** command attempts to pull images:
```
rschambach:sconectl/ (main✗) $ ./target/debug/sconectl apply --help                          [17:03:41]
Failed to "docker pull registry.scontain.com:5050/sconectl/sconecli:latest"! Do you have access rights? Please check and send email to info@scontain.com if you need access. (Error 24501-25270-6605)
⡃⠀     0.511 s	Pulling image 'registry.scontain.com:5050/sconectl/sconecli:latest'

Failed to 'docker pull registry.scontain.com:5050/sconectl/sconecli:latest'! Do you have access rights? Please check and send email to info@scontain.com if you need access. (Error 24501-25270-6605)
⠅⠀     0.400 s	Executing command 'apply'scone apply 0.1.0
SCONE Team

```

**Comment by SilvaMatteus** [comment]
Hi @enterJazz. Thanks for opening this issue.

It happens because the apply command itself is a command that comes from a docker image (`registry.scontain.com:5050/sconectl/sconecli`).

In fact, the only function of `sconectl` is to call a containter image and pass the command along.

Once you have the docker image, the command will work as you expect.

@scontain, could you give access to @enterJazz?

**Comment by scontain** [comment]
Done - should work now.
